# Generated by Django 5.0.6 on 2024-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_remove_orderitem_order_remove_rentaddress_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('colors', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='cars/')),
                ('additional_images', models.ManyToManyField(to='car_rental.carimage')),
            ],
        ),
    ]
