# Generated by Django 5.0.6 on 2024-06-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_carimage_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='additional_images',
            field=models.ManyToManyField(related_name='cars', to='car_rental.carimage'),
        ),
    ]
