# Generated by Django 5.0.6 on 2024-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0004_booking_total_cost_alter_car_additional_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_cost",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
